version: '3.8'

services:
  db:
    image: postgres:15
    container_name: nextjs_postgres
    restart: always
    environment:
      POSTGRES_USER: nextuser
      POSTGRES_PASSWORD: nextpass
      POSTGRES_DB: nextdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: